name: Run Yearly Scraper

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  run-docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (optional if you don't use repo files)
        uses: actions/checkout@v3

      - name: Run prebuilt Docker image and generate CSV
        run: docker run --rm -v ${{ github.workspace }}/output:/app/static schwandersc/baseball_schedule:latest

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-csv
          path: output/final_draft.csv

