name: Scrape MLB Schedule

on:
  workflow_dispatch:

jobs:
  scrape-mlb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run MLB scraper
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output/mlb:/app/static \
            schwandersc/schedules:latest mlb

      - name: Upload MLB schedule
        uses: actions/upload-artifact@v4
        with:
          name: mlb-schedule
          path: output/mlb/
