name: Scrape WNBA Schedule

on:
  workflow_dispatch:

jobs:
  scrape-wnba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run WNBA scraper
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output/wnba:/app/static \
            schwandersc/schedules:latest wnba

      - name: Upload WNBA schedule
        uses: actions/upload-artifact@v4
        with:
          name: wnba-schedule
          path: output/wnba/
